version: "3"

services:
  api:
    build: .
    volumes:
      - .:/usr/app
    ports:
      - 3000:8080
    depends_on:
      - db
    environment:
      NODE_ENV: "development"
  db:
    image: mysql:5.7.31
    ports:
      - 5432:5432
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_NAME=${DATABASE_NAME}
